chrome.omnibox.onInputChanged.addListener(
  function(text, suggest) {
    var links = [
      {description:'Artisan / Introduction',content:'http://laravel.com/docs/5.0/artisan/#introduction'},
      {description:'Artisan / Usage',content:'http://laravel.com/docs/5.0/artisan/#usage'},
      {description:'Artisan / Calling Commands Outside Of CLI',content:'http://laravel.com/docs/5.0/artisan/#calling-commands-outside-of-cli'},
      {description:'Artisan / Scheduling Artisan Commands',content:'http://laravel.com/docs/5.0/artisan/#scheduling-Artisan-commands'},
      {description:'Authentication / Introduction',content:'http://laravel.com/docs/5.0/authentication/#introduction'},
      {description:'Authentication / Authenticating Users',content:'http://laravel.com/docs/5.0/authentication/#authenticating-users'},
      {description:'Authentication / Retrieving The Authenticated User',content:'http://laravel.com/docs/5.0/authentication/#retrieving-the-authenticated-user'},
      {description:'Authentication / Protecting Routes',content:'http://laravel.com/docs/5.0/authentication/#protecting-routes'},
      {description:'Authentication / HTTP Basic Authentication',content:'http://laravel.com/docs/5.0/authentication/#http-basic-Authentication'},
      {description:'Authentication / Password Reminders & Reset',content:'http://laravel.com/docs/5.0/authentication/#password-reminders-and-reset'},
      {description:'Authentication / Social Authentication',content:'http://laravel.com/docs/5.0/authentication/#social-Authentication'},
      {description:'Billing / Introduction',content:'http://laravel.com/docs/5.0/billing/#introduction'},
      {description:'Billing / Configuration',content:'http://laravel.com/docs/5.0/billing/#configuration'},
      {description:'Billing / Subscribing To A Plan',content:'http://laravel.com/docs/5.0/billing/#subscribing-to-a-plan'},
      {description:'Billing / Single Charges',content:'http://laravel.com/docs/5.0/billing/#single-charges'},
      {description:'Billing / No Card Up Front',content:'http://laravel.com/docs/5.0/billing/#no-card-up-front'},
      {description:'Billing / Swapping Subscriptions',content:'http://laravel.com/docs/5.0/billing/#swapping-subscriptions'},
      {description:'Billing / Subscription Quantity',content:'http://laravel.com/docs/5.0/billing/#subscription-quantity'},
      {description:'Billing / Cancelling A Subscription',content:'http://laravel.com/docs/5.0/billing/#cancelling-a-subscription'},
      {description:'Billing / Resuming A Subscription',content:'http://laravel.com/docs/5.0/billing/#resuming-a-subscription'},
      {description:'Billing / Checking Subscription Status',content:'http://laravel.com/docs/5.0/billing/#checking-subscription-status'},
      {description:'Billing / Handling Failed Subscriptions',content:'http://laravel.com/docs/5.0/billing/#handling-failed-subscriptions'},
      {description:'Billing / Handling Other Stripe Webhooks',content:'http://laravel.com/docs/5.0/billing/#handling-other-stripe-webhooks'},
      {description:'Billing / Invoices',content:'http://laravel.com/docs/5.0/billing/#invoices'},
      {description:'Bus / Introduction',content:'http://laravel.com/docs/5.0/bus/#introduction'},
      {description:'Bus / Creating Commands',content:'http://laravel.com/docs/5.0/bus/#creating-commands'},
      {description:'Bus / Dispatching Commands',content:'http://laravel.com/docs/5.0/bus/#dispatching-commands'},
      {description:'Bus / Queued Commands',content:'http://laravel.com/docs/5.0/bus/#queued-commands'},
      {description:'Bus / Command Pipeline',content:'http://laravel.com/docs/5.0/bus/#command-pipeline'},
      {description:'Cache / Configuration',content:'http://laravel.com/docs/5.0/cache/#configuration'},
      {description:'Cache / Cache Usage',content:'http://laravel.com/docs/5.0/cache/#cache-usage'},
      {description:'Cache / Increments & Decrements',content:'http://laravel.com/docs/5.0/cache/#increments-and-decrements'},
      {description:'Cache / Cache Tags',content:'http://laravel.com/docs/5.0/cache/#cache-tags'},
      {description:'Cache / Cache Events',content:'http://laravel.com/docs/5.0/cache/#cache-events'},
      {description:'Cache / Database Cache',content:'http://laravel.com/docs/5.0/cache/#database-cache'},
      {description:'Cache / Memcached Cache',content:'http://laravel.com/docs/5.0/cache/#memcached-cache'},
      {description:'Cache / Redis Cache',content:'http://laravel.com/docs/5.0/cache/#redis-cache'},
      {description:'Collections / Introduction',content:'http://laravel.com/docs/5.0/collections/#introduction'},
      {description:'Collections / Basic Usage',content:'http://laravel.com/docs/5.0/collections/#basic-usage'},
      {description:'Commands / Introduction',content:'http://laravel.com/docs/5.0/commands/#introduction'},
      {description:'Commands / Building A Command',content:'http://laravel.com/docs/5.0/commands/#building-a-command'},
      {description:'Commands / Registering Commands',content:'http://laravel.com/docs/5.0/commands/#registering-commands'},
      {description:'Configuration / Introduction',content:'http://laravel.com/docs/5.0/configuration/#introduction'},
      {description:'Configuration / After Installation',content:'http://laravel.com/docs/5.0/configuration/#after-installation'},
      {description:'Configuration / Accessing Configuration Values',content:'http://laravel.com/docs/5.0/configuration/#accessing-configuration-values'},
      {description:'Configuration / Environment Configuration',content:'http://laravel.com/docs/5.0/configuration/#environment-configuration'},
      {description:'Configuration / Configuration Caching',content:'http://laravel.com/docs/5.0/configuration/#configuration-caching'},
      {description:'Configuration / Maintenance Mode',content:'http://laravel.com/docs/5.0/configuration/#maintenance-mode'},
      {description:'Configuration / Pretty URLs',content:'http://laravel.com/docs/5.0/configuration/#pretty-urls'},
      {description:'Container / Introduction',content:'http://laravel.com/docs/5.0/container/#introduction'},
      {description:'Container / Basic Usage',content:'http://laravel.com/docs/5.0/container/#basic-usage'},
      {description:'Container / Binding Interfaces To Implementations',content:'http://laravel.com/docs/5.0/container/#binding-interfaces-to-implementations'},
      {description:'Container / Contextual Binding',content:'http://laravel.com/docs/5.0/container/#contextual-binding'},
      {description:'Container / Tagging',content:'http://laravel.com/docs/5.0/container/#tagging'},
      {description:'Container / Practical Applications',content:'http://laravel.com/docs/5.0/container/#practical-applications'},
      {description:'Container / Container Events',content:'http://laravel.com/docs/5.0/container/#container-events'},
      {description:'Contracts / Introduction',content:'http://laravel.com/docs/5.0/container/#introduction'},
      {description:'Contracts / Why Contracts?',content:'http://laravel.com/docs/5.0/container/#why-contracts'},
      {description:'Contracts / Contract Reference',content:'http://laravel.com/docs/5.0/container/#contract-reference'},
      {description:'Contracts / How To Use Contracts',content:'http://laravel.com/docs/5.0/container/#how-to-use-contracts'},
      {description:'Contributions / Bug Reports',content:'http://laravel.com/docs/5.0/contributions/#bug-reports'},
      {description:'Contributions / Core Development Discussion',content:'http://laravel.com/docs/5.0/contributions/#core-development-discussion'},
      {description:'Contributions / Which Branch?',content:'http://laravel.com/docs/5.0/contributions/#which-branch'},
      {description:'Contributions / Security Vulnerabilities',content:'http://laravel.com/docs/5.0/contributions/#security-vulnerabilities'},
      {description:'Contributions / Coding Style',content:'http://laravel.com/docs/5.0/contributions/#coding-style'},
      {description:'Contributions / Laravel Framework',content:'http://laravel.com/docs/5.0/contributions/https://github.com/laravel/framework'},
      {description:'Contributions / Laravel Application',content:'http://laravel.com/docs/5.0/contributions/https://github.com/laravel/laravel'},
      {description:'Contributions / Laravel Documentation',content:'http://laravel.com/docs/5.0/contributions/https://github.com/laravel/docs'},
      {description:'Contributions / Laravel Cashier',content:'http://laravel.com/docs/5.0/contributions/https://github.com/laravel/cashier'},
      {description:'Contributions / Laravel Envoy',content:'http://laravel.com/docs/5.0/contributions/https://github.com/laravel/envoy'},
      {description:'Contributions / Laravel Homestead',content:'http://laravel.com/docs/5.0/contributions/https://github.com/laravel/homestead'},
      {description:'Contributions / Laravel Homestead Build Scripts',content:'http://laravel.com/docs/5.0/contributions/https://github.com/laravel/settler'},
      {description:'Contributions / Laravel Website',content:'http://laravel.com/docs/5.0/contributions/https://github.com/laravel/laravel.com'},
      {description:'Contributions / Laravel Art',content:'http://laravel.com/docs/5.0/contributions/https://github.com/laravel/art'},
      {description:'Controllers / Introduction',content:'http://laravel.com/docs/5.0/controllers/#introduction'},
      {description:'Controllers / Basic Controllers',content:'http://laravel.com/docs/5.0/controllers/#basic-controllers'},
      {description:'Controllers / Controller Middleware',content:'http://laravel.com/docs/5.0/controllers/#controller-middleware'},
      {description:'Controllers / Implicit Controllers',content:'http://laravel.com/docs/5.0/controllers/#implicit-controllers'},
      {description:'Controllers / RESTful Resource Controllers',content:'http://laravel.com/docs/5.0/controllers/#restful-resource-controllers'},
      {description:'Controllers / Dependency Injection & Controllers',content:'http://laravel.com/docs/5.0/controllers/#dependency-injection-and-controllers'},
      {description:'Controllers / Route Caching',content:'http://laravel.com/docs/5.0/controllers/#route-caching'},
      {description:'Database / Configuration',content:'http://laravel.com/docs/5.0/database/#configuration'},
      {description:'Database / Read / Write Connections',content:'http://laravel.com/docs/5.0/database/#read-write-connections'},
      {description:'Database / Running Queries',content:'http://laravel.com/docs/5.0/database/#running-queries'},
      {description:'Database / Database Transactions',content:'http://laravel.com/docs/5.0/database/#database-transactions'},
      {description:'Database / Accessing Connections',content:'http://laravel.com/docs/5.0/database/#accessing-connections'},
      {description:'Database / Query Logging',content:'http://laravel.com/docs/5.0/database/#query-logging'},
      {description:'Elixir / Introduction',content:'http://laravel.com/docs/5.0/elixir/#introduction'},
      {description:'Elixir / Installation & Setup',content:'http://laravel.com/docs/5.0/elixir/#installation'},
      {description:'Elixir / Usage',content:'http://laravel.com/docs/5.0/elixir/#usage'},
      {description:'Elixir / Gulp',content:'http://laravel.com/docs/5.0/elixir/#gulp'},
      {description:'Elixir / Extensions',content:'http://laravel.com/docs/5.0/elixir/#extensions'},
      {description:'Eloquent / Introduction',content:'http://laravel.com/docs/5.0/eloquent/#introduction'},
      {description:'Eloquent / Basic Usage',content:'http://laravel.com/docs/5.0/eloquent/#basic-usage'},
      {description:'Eloquent / Mass Assignment',content:'http://laravel.com/docs/5.0/eloquent/#mass-assignment'},
      {description:'Eloquent / Insert,Update,Delete',content:'http://laravel.com/docs/5.0/eloquent/#insert-update-delete'},
      {description:'Eloquent / Soft Deleting',content:'http://laravel.com/docs/5.0/eloquent/#soft-deleting'},
      {description:'Eloquent / Timestamps',content:'http://laravel.com/docs/5.0/eloquent/#timestamps'},
      {description:'Eloquent / Query Scopes',content:'http://laravel.com/docs/5.0/eloquent/#query-scopes'},
      {description:'Eloquent / Global Scopes',content:'http://laravel.com/docs/5.0/eloquent/#global-scopes'},
      {description:'Eloquent / Relationships',content:'http://laravel.com/docs/5.0/eloquent/#relationships'},
      {description:'Eloquent / Querying Relations',content:'http://laravel.com/docs/5.0/eloquent/#querying-relations'},
      {description:'Eloquent / Eager Loading',content:'http://laravel.com/docs/5.0/eloquent/#eager-loading'},
      {description:'Eloquent / Inserting Related Models',content:'http://laravel.com/docs/5.0/eloquent/#inserting-related-models'},
      {description:'Eloquent / Touching Parent Timestamps',content:'http://laravel.com/docs/5.0/eloquent/#touching-parent-timestamps'},
      {description:'Eloquent / Working With Pivot Tables',content:'http://laravel.com/docs/5.0/eloquent/#working-with-pivot-tables'},
      {description:'Eloquent / Collections',content:'http://laravel.com/docs/5.0/eloquent/#collections'},
      {description:'Eloquent / Accessors & Mutators',content:'http://laravel.com/docs/5.0/eloquent/#accessors-and-mutators'},
      {description:'Eloquent / Date Mutators',content:'http://laravel.com/docs/5.0/eloquent/#date-mutators'},
      {description:'Eloquent / Attribute Casting',content:'http://laravel.com/docs/5.0/eloquent/#attribute-casting'},
      {description:'Eloquent / Model Events',content:'http://laravel.com/docs/5.0/eloquent/#model-events'},
      {description:'Eloquent / Model Observers',content:'http://laravel.com/docs/5.0/eloquent/#model-observers'},
      {description:'Eloquent / Model URL Generation',content:'http://laravel.com/docs/5.0/eloquent/#model-url-generation'},
      {description:'Eloquent / Converting To Arrays / JSON',content:'http://laravel.com/docs/5.0/eloquent/#converting-to-arrays-or-json'},
      {description:'Eloquent / One To One',content:'http://laravel.com/docs/5.0/eloquent/#one-to-one'},
      {description:'Eloquent / One To Many',content:'http://laravel.com/docs/5.0/eloquent/#one-to-many'},
      {description:'Eloquent / Many To Many',content:'http://laravel.com/docs/5.0/eloquent/#many-to-many'},
      {description:'Eloquent / Has Many Through',content:'http://laravel.com/docs/5.0/eloquent/#has-many-through'},
      {description:'Eloquent / Polymorphic Relations',content:'http://laravel.com/docs/5.0/eloquent/#polymorphic-relations'},
      {description:'Eloquent / Many To Many Polymorphic Relations',content:'http://laravel.com/docs/5.0/eloquent/#many-to-many-polymorphic-relations'},
      {description:'Encryption / Introduction',content:'http://laravel.com/docs/5.0/encryption/#introduction'},
      {description:'Encryption / Basic Usage',content:'http://laravel.com/docs/5.0/encryption/#basic-usage'},
      {description:'Envoy / Introduction',content:'http://laravel.com/docs/5.0/envoy/#introduction'},
      {description:'Envoy / Installation',content:'http://laravel.com/docs/5.0/envoy/#envoy-installation'},
      {description:'Envoy / Running Tasks',content:'http://laravel.com/docs/5.0/envoy/#envoy-running-tasks'},
      {description:'Envoy / Multiple Servers',content:'http://laravel.com/docs/5.0/envoy/#envoy-multiple-servers'},
      {description:'Envoy / Parallel Execution',content:'http://laravel.com/docs/5.0/envoy/#envoy-parallel-execution'},
      {description:'Envoy / Task Macros',content:'http://laravel.com/docs/5.0/envoy/#envoy-task-macros'},
      {description:'Envoy / Notifications',content:'http://laravel.com/docs/5.0/envoy/#envoy-notifications'},
      {description:'Envoy / Updating Envoy',content:'http://laravel.com/docs/5.0/envoy/#envoy-updating-envoy'},
      {description:'Errors / Configuration',content:'http://laravel.com/docs/5.0/errors/#configuration'},
      {description:'Errors / Handling Errors',content:'http://laravel.com/docs/5.0/errors/#handling-errors'},
      {description:'Errors / HTTP Exceptions',content:'http://laravel.com/docs/5.0/errors/#http-exceptions'},
      {description:'Errors / Logging',content:'http://laravel.com/docs/5.0/errors/#logging'},
      {description:'Events / Basic Usage',content:'http://laravel.com/docs/5.0/events/#basic-usage'},
      {description:'Events / Queued Event Handlers',content:'http://laravel.com/docs/5.0/events/#queued-event-handlers'},
      {description:'Events / Event Subscribers',content:'http://laravel.com/docs/5.0/events/#event-subscribers'},
      {description:'Extending / Managers & Factories',content:'http://laravel.com/docs/5.0/extending/#managers-and-factories'},
      {description:'Extending / Cache',content:'http://laravel.com/docs/5.0/extending/#cache'},
      {description:'Extending / Session',content:'http://laravel.com/docs/5.0/extending/#session'},
      {description:'Extending / Authentication',content:'http://laravel.com/docs/5.0/extending/#authentication'},
      {description:'Extending / Service Container Based Extension',content:'http://laravel.com/docs/5.0/extending/#container-based-extension'},
      {description:'Facades / Introduction',content:'http://laravel.com/docs/5.0/facades/#introduction'},
      {description:'Facades / Explanation',content:'http://laravel.com/docs/5.0/facades/#explanation'},
      {description:'Facades / Practical Usage',content:'http://laravel.com/docs/5.0/facades/#practical-usage'},
      {description:'Facades / Creating Facades',content:'http://laravel.com/docs/5.0/facades/#creating-facades'},
      {description:'Facades / Mocking Facades',content:'http://laravel.com/docs/5.0/facades/#mocking-facades'},
      {description:'Facades / Facade Class Reference',content:'http://laravel.com/docs/5.0/facades/#facade-class-reference'},
      {description:'Filesystem / Introduction',content:'http://laravel.com/docs/5.0/filesystem/#introduction'},
      {description:'Filesystem / Configuration',content:'http://laravel.com/docs/5.0/filesystem/#configuration'},
      {description:'Filesystem / Basic Usage',content:'http://laravel.com/docs/5.0/filesystem/#basic-usage'},
      {description:'Filesystem / Custom Filesystems',content:'http://laravel.com/docs/5.0/filesystem/#custom-filesystems'},
      {description:'Hashing / Introduction',content:'http://laravel.com/docs/5.0/hashing/#introduction'},
      {description:'Hashing / Basic Usage',content:'http://laravel.com/docs/5.0/hashing/#basic-usage'},
      {description:'Helpers / Arrays',content:'http://laravel.com/docs/5.0/helpers/#arrays'},
      {description:'Helpers / Paths',content:'http://laravel.com/docs/5.0/helpers/#paths'},
      {description:'Helpers / Routing',content:'http://laravel.com/docs/5.0/helpers/#routing'},
      {description:'Helpers / Strings',content:'http://laravel.com/docs/5.0/helpers/#strings'},
      {description:'Helpers / URLs',content:'http://laravel.com/docs/5.0/helpers/#urls'},
      {description:'Helpers / Miscellaneous',content:'http://laravel.com/docs/5.0/helpers/#miscellaneous'},
      {description:'Homestead / Introduction',content:'http://laravel.com/docs/5.0/homestead/#introduction'},
      {description:'Homestead / Included Software',content:'http://laravel.com/docs/5.0/homestead/#included-software'},
      {description:'Homestead / Installation & Setup',content:'http://laravel.com/docs/5.0/homestead/#installation-and-setup'},
      {description:'Homestead / Daily Usage',content:'http://laravel.com/docs/5.0/homestead/#daily-usage'},
      {description:'Homestead / Ports',content:'http://laravel.com/docs/5.0/homestead/#ports'},
      {description:'Homestead / Blackfire Profiler',content:'http://laravel.com/docs/5.0/homestead/#blackfire-profiler'},
      {description:'Homestead / Laravel Envoy',content:'http://laravel.com/docs/5.0/homestead//docs/5.0/envoy'},
      {description:'Homestead / Blackfire Profiler',content:'http://laravel.com/docs/5.0/homestead/#blackfire-profiler'},
      {description:'Installation / Install Composer',content:'http://laravel.com/docs/5.0/installation/#install-composer'},
      {description:'Installation / Install Laravel',content:'http://laravel.com/docs/5.0/installation/#install-laravel'},
      {description:'Installation / Server Requirements',content:'http://laravel.com/docs/5.0/installation/#server-requirements'},
      {description:'Lifecycle / Introduction',content:'http://laravel.com/docs/5.0/lifecycle/#introduction'},
      {description:'Lifecycle / Lifecycle Overview',content:'http://laravel.com/docs/5.0/lifecycle/#lifecycle-overview'},
      {description:'Lifecycle / Focus On Service Providers',content:'http://laravel.com/docs/5.0/lifecycle/#focus-on-service-providers'},
      {description:'Localization / Introduction',content:'http://laravel.com/docs/5.0/localization/#introduction'},
      {description:'Localization / Language Files',content:'http://laravel.com/docs/5.0/localization/#language-files'},
      {description:'Localization / Basic Usage',content:'http://laravel.com/docs/5.0/localization/#basic-usage'},
      {description:'Localization / Pluralization',content:'http://laravel.com/docs/5.0/localization/#pluralization'},
      {description:'Localization / Validation Localization',content:'http://laravel.com/docs/5.0/localization/#validation'},
      {description:'Localization / Overriding Package Language Files',content:'http://laravel.com/docs/5.0/localization/#overriding-package-language-files'},
      {description:'Mail / Configuration',content:'http://laravel.com/docs/5.0/mail/#configuration'},
      {description:'Mail / Basic Usage',content:'http://laravel.com/docs/5.0/mail/#basic-usage'},
      {description:'Mail / Embedding Inline Attachments',content:'http://laravel.com/docs/5.0/mail/#embedding-inline-attachments'},
      {description:'Mail / Queueing Mail',content:'http://laravel.com/docs/5.0/mail/#queueing-mail'},
      {description:'Mail / Mail & Local Development',content:'http://laravel.com/docs/5.0/mail/#mail-and-local-development'},
      {description:'Middleware / Introduction',content:'http://laravel.com/docs/5.0/middleware/#introduction'},
      {description:'Middleware / Defining Middleware',content:'http://laravel.com/docs/5.0/middleware/#defining-middleware'},
      {description:'Middleware / Registering Middleware',content:'http://laravel.com/docs/5.0/middleware/#registering-middleware'},
      {description:'Middleware / Terminable Middleware',content:'http://laravel.com/docs/5.0/middleware/#terminable-middleware'},
      {description:'Migrations / Introduction',content:'http://laravel.com/docs/5.0/migrations/#introduction'},
      {description:'Migrations / Creating Migrations',content:'http://laravel.com/docs/5.0/migrations/#creating-migrations'},
      {description:'Migrations / Running Migrations',content:'http://laravel.com/docs/5.0/migrations/#running-migrations'},
      {description:'Migrations / Rolling Back Migrations',content:'http://laravel.com/docs/5.0/migrations/#rolling-back-migrations'},
      {description:'Migrations / Database Seeding',content:'http://laravel.com/docs/5.0/migrations/#database-seeding'},
      {description:'Packages / Introduction',content:'http://laravel.com/docs/5.0/packages/#introduction'},
      {description:'Packages / Views',content:'http://laravel.com/docs/5.0/packages/#views'},
      {description:'Packages / Translations',content:'http://laravel.com/docs/5.0/packages/#translations'},
      {description:'Packages / Configuration',content:'http://laravel.com/docs/5.0/packages/#configuration'},
      {description:'Packages / Public Assets',content:'http://laravel.com/docs/5.0/packages/#public-assets'},
      {description:'Packages / Publishing File Groups',content:'http://laravel.com/docs/5.0/packages/#publishing-file-groups'},
      {description:'Packages / Routing',content:'http://laravel.com/docs/5.0/packages/#routing'},
      {description:'Pagination / Configuration',content:'http://laravel.com/docs/5.0/pagination/#configuration'},
      {description:'Pagination / Usage',content:'http://laravel.com/docs/5.0/pagination/#usage'},
      {description:'Pagination / Appending To Pagination Links',content:'http://laravel.com/docs/5.0/pagination/#appending-to-pagination-links'},
      {description:'Pagination / Converting To JSON',content:'http://laravel.com/docs/5.0/pagination/#converting-to-json'},
      {description:'Providers / Introduction',content:'http://laravel.com/docs/5.0/providers/#introduction'},
      {description:'Providers / Basic Provider Example',content:'http://laravel.com/docs/5.0/providers/#basic-provider-example'},
      {description:'Providers / Registering Providers',content:'http://laravel.com/docs/5.0/providers/#registering-providers'},
      {description:'Providers / Deferred Providers',content:'http://laravel.com/docs/5.0/providers/#deferred-providers'},
      {description:'Queries / Introduction',content:'http://laravel.com/docs/5.0/queries/#introduction'},
      {description:'Queries / Selects',content:'http://laravel.com/docs/5.0/queries/#selects'},
      {description:'Queries / Joins',content:'http://laravel.com/docs/5.0/queries/#joins'},
      {description:'Queries / Advanced Wheres',content:'http://laravel.com/docs/5.0/queries/#advanced-wheres'},
      {description:'Queries / Aggregates',content:'http://laravel.com/docs/5.0/queries/#aggregates'},
      {description:'Queries / Raw Expressions',content:'http://laravel.com/docs/5.0/queries/#raw-expressions'},
      {description:'Queries / Inserts',content:'http://laravel.com/docs/5.0/queries/#inserts'},
      {description:'Queries / Updates',content:'http://laravel.com/docs/5.0/queries/#updates'},
      {description:'Queries / Deletes',content:'http://laravel.com/docs/5.0/queries/#deletes'},
      {description:'Queries / Unions',content:'http://laravel.com/docs/5.0/queries/#unions'},
      {description:'Queries / Pessimistic Locking',content:'http://laravel.com/docs/5.0/queries/#pessimistic-locking'},
      {description:'Queues / Configuration',content:'http://laravel.com/docs/5.0/queues/#configuration'},
      {description:'Queues / Basic Usage',content:'http://laravel.com/docs/5.0/queues/#basic-usage'},
      {description:'Queues / Queueing Closures',content:'http://laravel.com/docs/5.0/queues/#queueing-closures'},
      {description:'Queues / Running The Queue Listener',content:'http://laravel.com/docs/5.0/queues/#running-the-queue-listener'},
      {description:'Queues / Daemon Queue Worker',content:'http://laravel.com/docs/5.0/queues/#daemon-queue-worker'},
      {description:'Queues / Push Queues',content:'http://laravel.com/docs/5.0/queues/#push-queues'},
      {description:'Queues / Failed Jobs',content:'http://laravel.com/docs/5.0/queues/#failed-jobs'},
      {description:'Redis / Introduction',content:'http://laravel.com/docs/5.0/redis/#introduction'},
      {description:'Redis / Configuration',content:'http://laravel.com/docs/5.0/redis/#configuration'},
      {description:'Redis / Usage',content:'http://laravel.com/docs/5.0/redis/#usage'},
      {description:'Redis / Pipelining',content:'http://laravel.com/docs/5.0/redis/#pipelining'},
      {description:'Releases / Support Policy',content:'http://laravel.com/docs/5.0/releases/#support-policy'},
      {description:'Releases / Laravel 5.0',content:'http://laravel.com/docs/5.0/releases/#laravel-5.0'},
      {description:'Releases / Laravel 4.2',content:'http://laravel.com/docs/5.0/releases/#laravel-4.2'},
      {description:'Releases / Laravel 4.1',content:'http://laravel.com/docs/5.0/releases/#laravel-4.1'},
      {description:'Requests / Obtaining A Request Instance',content:'http://laravel.com/docs/5.0/requests/#obtaining-a-request-instance'},
      {description:'Requests / Retrieving Input',content:'http://laravel.com/docs/5.0/requests/#retrieving-input'},
      {description:'Requests / Old Input',content:'http://laravel.com/docs/5.0/requests/#old-input'},
      {description:'Requests / Cookies',content:'http://laravel.com/docs/5.0/requests/#cookies'},
      {description:'Requests / Files',content:'http://laravel.com/docs/5.0/requests/#files'},
      {description:'Requests / Other Request Information',content:'http://laravel.com/docs/5.0/requests/#other-request-information'},
      {description:'Responses / Basic Responses',content:'http://laravel.com/docs/5.0/responses/#basic-responses'},
      {description:'Responses / Redirects',content:'http://laravel.com/docs/5.0/responses/#redirects'},
      {description:'Responses / Other Responses',content:'http://laravel.com/docs/5.0/responses/#other-responses'},
      {description:'Responses / Response Macros',content:'http://laravel.com/docs/5.0/responses/#response-macros'},
      {description:'Routing / Basic Routing',content:'http://laravel.com/docs/5.0/routing/#basic-routing'},
      {description:'Routing / CSRF Protection',content:'http://laravel.com/docs/5.0/routing/#csrf-protection'},
      {description:'Routing / Method Spoofing',content:'http://laravel.com/docs/5.0/routing/#method-spoofing'},
      {description:'Routing / Route Parameters',content:'http://laravel.com/docs/5.0/routing/#route-parameters'},
      {description:'Routing / Named Routes',content:'http://laravel.com/docs/5.0/routing/#named-routes'},
      {description:'Routing / Route Groups',content:'http://laravel.com/docs/5.0/routing/#route-groups'},
      {description:'Routing / Route Model Binding',content:'http://laravel.com/docs/5.0/routing/#route-model-binding'},
      {description:'Routing / Throwing 404 Errors',content:'http://laravel.com/docs/5.0/routing/#throwing-404-errors'},
      {description:'Schema / Introduction',content:'http://laravel.com/docs/5.0/schema/#introduction'},
      {description:'Schema / Creating & Dropping Tables',content:'http://laravel.com/docs/5.0/schema/#creating-and-dropping-tables'},
      {description:'Schema / Adding Columns',content:'http://laravel.com/docs/5.0/schema/#adding-columns'},
      {description:'Schema / Changing Columns',content:'http://laravel.com/docs/5.0/schema/#changing-columns'},
      {description:'Schema / Renaming Columns',content:'http://laravel.com/docs/5.0/schema/#renaming-columns'},
      {description:'Schema / Dropping Columns',content:'http://laravel.com/docs/5.0/schema/#dropping-columns'},
      {description:'Schema / Checking Existence',content:'http://laravel.com/docs/5.0/schema/#checking-existence'},
      {description:'Schema / Adding Indexes',content:'http://laravel.com/docs/5.0/schema/#adding-indexes'},
      {description:'Schema / Foreign Keys',content:'http://laravel.com/docs/5.0/schema/#foreign-keys'},
      {description:'Schema / Dropping Indexes',content:'http://laravel.com/docs/5.0/schema/#dropping-indexes'},
      {description:'Schema / Dropping Timestamps & Soft Deletes',content:'http://laravel.com/docs/5.0/schema/#dropping-timestamps'},
      {description:'Schema / Storage Engines',content:'http://laravel.com/docs/5.0/schema/#storage-engines'},
      {description:'Session / Configuration',content:'http://laravel.com/docs/5.0/session/#configuration'},
      {description:'Session / Session Usage',content:'http://laravel.com/docs/5.0/session/#session-usage'},
      {description:'Session / Flash Data',content:'http://laravel.com/docs/5.0/session/#flash-data'},
      {description:'Session / Database Sessions',content:'http://laravel.com/docs/5.0/session/#database-sessions'},
      {description:'Session / Session Drivers',content:'http://laravel.com/docs/5.0/session/#session-drivers'},
      {description:'Structure / Introduction',content:'http://laravel.com/docs/5.0/structure/#introduction'},
      {description:'Structure / The Root Directory',content:'http://laravel.com/docs/5.0/structure/#the-root-directory'},
      {description:'Structure / The App Directory',content:'http://laravel.com/docs/5.0/structure/#the-app-directory'},
      {description:'Structure / Namespacing Your Application',content:'http://laravel.com/docs/5.0/structure/#namespacing-your-application'},
      {description:'Templates / Blade Templating',content:'http://laravel.com/docs/5.0/templates/#blade-templating'},
      {description:'Templates / Other Blade Control Structures',content:'http://laravel.com/docs/5.0/templates/#other-blade-control-structures'},
      {description:'Testing / Introduction',content:'http://laravel.com/docs/5.0/testing/#introduction'},
      {description:'Testing / Defining & Running Tests',content:'http://laravel.com/docs/5.0/testing/#defining-and-running-tests'},
      {description:'Testing / Test Environment',content:'http://laravel.com/docs/5.0/testing/#test-environment'},
      {description:'Testing / Calling Routes From Tests',content:'http://laravel.com/docs/5.0/testing/#calling-routes-from-tests'},
      {description:'Testing / Mocking Facades',content:'http://laravel.com/docs/5.0/testing/#mocking-facades'},
      {description:'Testing / Framework Assertions',content:'http://laravel.com/docs/5.0/testing/#framework-assertions'},
      {description:'Testing / Helper Methods',content:'http://laravel.com/docs/5.0/testing/#helper-methods'},
      {description:'Testing / Refreshing The Application',content:'http://laravel.com/docs/5.0/testing/#refreshing-the-application'},
      {description:'Upgrade / Upgrading To 5.0.16',content:'http://laravel.com/docs/5.0/upgrade/#upgrade-5.0.16'},
      {description:'Upgrade / Upgrading To 5.0 From 4.2',content:'http://laravel.com/docs/5.0/upgrade/#upgrade-5.0'},
      {description:'Upgrade / Upgrading To 4.2 From 4.1',content:'http://laravel.com/docs/5.0/upgrade/#upgrade-4.2'},
      {description:'Upgrade / Upgrading To 4.1.29 From <= 4.1.x',content:'http://laravel.com/docs/5.0/upgrade/#upgrade-4.1.29'},
      {description:'Upgrade / Upgrading To 4.1.26 From <= 4.1.25',content:'http://laravel.com/docs/5.0/upgrade/#upgrade-4.1.26'},
      {description:'Upgrade / Upgrading To 4.1 From 4.0',content:'http://laravel.com/docs/5.0/upgrade/#upgrade-4.1'},
      {description:'Validation / Basic Usage',content:'http://laravel.com/docs/5.0/validation/#basic-usage'},
      {description:'Validation / Controller Validation',content:'http://laravel.com/docs/5.0/validation/#controller-validation'},
      {description:'Validation / Form Request Validation',content:'http://laravel.com/docs/5.0/validation/#form-request-validation'},
      {description:'Validation / Working With Error Messages',content:'http://laravel.com/docs/5.0/validation/#working-with-error-messages'},
      {description:'Validation / Error Messages & Views',content:'http://laravel.com/docs/5.0/validation/#error-messages-and-views'},
      {description:'Validation / Available Validation Rules',content:'http://laravel.com/docs/5.0/validation/#available-validation-rules'},
      {description:'Validation / Conditionally Adding Rules',content:'http://laravel.com/docs/5.0/validation/#conditionally-adding-rules'},
      {description:'Validation / Custom Error Messages',content:'http://laravel.com/docs/5.0/validation/#custom-error-messages'},
      {description:'Validation / Custom Validation Rules',content:'http://laravel.com/docs/5.0/validation/#custom-validation-rules'},
      {description:'Validation / Accepted',content:'http://laravel.com/docs/5.0/validation/#rule-accepted'},
      {description:'Validation / Active URL',content:'http://laravel.com/docs/5.0/validation/#rule-active-url'},
      {description:'Validation / After (Date)',content:'http://laravel.com/docs/5.0/validation/#rule-after'},
      {description:'Validation / Alpha',content:'http://laravel.com/docs/5.0/validation/#rule-alpha'},
      {description:'Validation / Alpha Dash',content:'http://laravel.com/docs/5.0/validation/#rule-alpha-dash'},
      {description:'Validation / Alpha Numeric',content:'http://laravel.com/docs/5.0/validation/#rule-alpha-num'},
      {description:'Validation / Array',content:'http://laravel.com/docs/5.0/validation/#rule-array'},
      {description:'Validation / Before (Date)',content:'http://laravel.com/docs/5.0/validation/#rule-before'},
      {description:'Validation / Between',content:'http://laravel.com/docs/5.0/validation/#rule-between'},
      {description:'Validation / Boolean',content:'http://laravel.com/docs/5.0/validation/#rule-boolean'},
      {description:'Validation / Confirmed',content:'http://laravel.com/docs/5.0/validation/#rule-confirmed'},
      {description:'Validation / Date',content:'http://laravel.com/docs/5.0/validation/#rule-date'},
      {description:'Validation / Date Format',content:'http://laravel.com/docs/5.0/validation/#rule-date-format'},
      {description:'Validation / Different',content:'http://laravel.com/docs/5.0/validation/#rule-different'},
      {description:'Validation / Digits',content:'http://laravel.com/docs/5.0/validation/#rule-digits'},
      {description:'Validation / Digits Between',content:'http://laravel.com/docs/5.0/validation/#rule-digits-between'},
      {description:'Validation / E-Mail',content:'http://laravel.com/docs/5.0/validation/#rule-email'},
      {description:'Validation / Exists (Database)',content:'http://laravel.com/docs/5.0/validation/#rule-exists'},
      {description:'Validation / Image (File)',content:'http://laravel.com/docs/5.0/validation/#rule-image'},
      {description:'Validation / In',content:'http://laravel.com/docs/5.0/validation/#rule-in'},
      {description:'Validation / Integer',content:'http://laravel.com/docs/5.0/validation/#rule-integer'},
      {description:'Validation / IP Address',content:'http://laravel.com/docs/5.0/validation/#rule-ip'},
      {description:'Validation / Max',content:'http://laravel.com/docs/5.0/validation/#rule-max'},
      {description:'Validation / MIME Types',content:'http://laravel.com/docs/5.0/validation/#rule-mimes'},
      {description:'Validation / Min',content:'http://laravel.com/docs/5.0/validation/#rule-min'},
      {description:'Validation / Not In',content:'http://laravel.com/docs/5.0/validation/#rule-not-in'},
      {description:'Validation / Numeric',content:'http://laravel.com/docs/5.0/validation/#rule-numeric'},
      {description:'Validation / Regular Expression',content:'http://laravel.com/docs/5.0/validation/#rule-regex'},
      {description:'Validation / Required',content:'http://laravel.com/docs/5.0/validation/#rule-required'},
      {description:'Validation / Required If',content:'http://laravel.com/docs/5.0/validation/#rule-required-if'},
      {description:'Validation / Required With',content:'http://laravel.com/docs/5.0/validation/#rule-required-with'},
      {description:'Validation / Required With All',content:'http://laravel.com/docs/5.0/validation/#rule-required-with-all'},
      {description:'Validation / Required Without',content:'http://laravel.com/docs/5.0/validation/#rule-required-without'},
      {description:'Validation / Required Without All',content:'http://laravel.com/docs/5.0/validation/#rule-required-without-all'},
      {description:'Validation / Same',content:'http://laravel.com/docs/5.0/validation/#rule-same'},
      {description:'Validation / Size',content:'http://laravel.com/docs/5.0/validation/#rule-size'},
      {description:'Validation / String',content:'http://laravel.com/docs/5.0/validation/#rule-string'},
      {description:'Validation / Timezone',content:'http://laravel.com/docs/5.0/validation/#rule-timezone'},
      {description:'Validation / Unique (Database)',content:'http://laravel.com/docs/5.0/validation/#rule-unique'},
      {description:'Validation / URL',content:'http://laravel.com/docs/5.0/validation/#rule-url'},
      {description:'Views / Basic Usage',content:'http://laravel.com/docs/5.0/views/#basic-usage'},
      {description:'Views / View Composers',content:'http://laravel.com/docs/5.0/views/#view-composers'}
  ]; 

    var result = links.filter(function(row) {
      if (row.description.toLowerCase().indexOf(text.toLowerCase()) > -1) {
        return true;
      } else {
        return false;
      }
    });
    
    suggest(links.filter(function(row) {
      if (row.description.toLowerCase().indexOf(text.toLowerCase()) > -1) {
        return true;
      } else {
        return false;
      }
    }));
  });

// This event is fired with the user accepts the input in the omnibox.
chrome.omnibox.onInputEntered.addListener(function(text) {
    chrome.tabs.create({ url: text });
});
